language: node_js
node_js:
- lts/*
addons:
  ssh_known_hosts: 35.233.171.1
script:
- npm test
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"
- if [ "$BRANCH" == "master" ]; then
    echo "production";
    openssl aes-256-cbc -K $encrypted_482956e64e81_key -iv $encrypted_482956e64e81_iv -in web-worker-key.enc -out /tmp/web-worker-key -d;
    chmod 600 /tmp/web-worker-key;
    eval `ssh-agent`;
    ssh-add /tmp/web-worker-key;
    ssh web-worker@35.233.171.1 "cd repositories/touhou-mix-server-nodejs/ && git pull && npm ci && pm2 restart thmix-server";
    kill $SSH_AGENT_PID;
  fi
- if [ "$BRANCH" == "staging" ]; then
    echo "staging";
    openssl aes-256-cbc -K $encrypted_482956e64e81_key -iv $encrypted_482956e64e81_iv -in web-worker-key.enc -out /tmp/web-worker-key -d;
    chmod 600 /tmp/web-worker-key;
    eval `ssh-agent`;
    ssh-add /tmp/web-worker-key;
    ssh web-worker@35.233.171.1 "cd repositories/touhou-mix-server-nodejs/ && git pull && npm ci && pm2 restart thmix-server-staging";
    kill $SSH_AGENT_PID;
  fi
