language: node_js
node_js:
- 11.0.0
addons:
  ssh_known_hosts: ssh.thmix.org
script:
- npm test
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"
- if [ "$BRANCH" == "master" ]; then
    echo "push to prod";
    openssl aes-256-cbc -K $encrypted_9db1b9bc09a9_key -iv $encrypted_9db1b9bc09a9_iv -in web-worker-key.enc -out /tmp/web-worker-key -d;
    chmod 600 /tmp/web-worker-key;
    eval `ssh-agent`;
    ssh-add /tmp/web-worker-key;
    ssh web-worker@ssh.thmix.org "cd repo/touhou-mix-server-nodejs/ && git pull && npm ci && pm2 restart thmix-sv";
    kill $SSH_AGENT_PID;
  fi