module.exports = [
  {albumIndex: 1, track: 1, name: 'A Sacred Lot'},
  {albumIndex: 1, track: 2, name: '永遠の巫女'},
  {albumIndex: 1, track: 3, name: 'The Positive and Negative'},
  {albumIndex: 1, track: 4, name: 'Highly Responsive to Prayers'},
  {albumIndex: 1, track: 5, name: '東方怪奇談'},
  {albumIndex: 1, track: 6, name: '天使伝説'},
  {albumIndex: 1, track: 7, name: 'Oriental Magician'},
  {albumIndex: 1, track: 8, name: '破邪の小太刀'},
  {albumIndex: 1, track: 9, name: '魔鏡'},
  {albumIndex: 1, track: 10, name: 'The Legend of KAGE'},
  {albumIndex: 1, track: 11, name: 'いざ、倒れ逝くその時まで'},
  {albumIndex: 1, track: 12, name: '死なばもろとも'},
  {albumIndex: 1, track: 13, name: '星幽剣士'},
  {albumIndex: 1, track: 14, name: 'アイリス'},
  {albumIndex: 1, track: 15, name: '風の神社'},

  {albumIndex: 2, track: 1, name: '東方封魔録　～浄土曼荼羅'},
  {albumIndex: 2, track: 2, name: '博麗　～Eastern Wind'},
  {albumIndex: 2, track: 3, name: 'She\'s in a temper!!'},
  {albumIndex: 2, track: 4, name: 'End of Daylight'},
  {albumIndex: 2, track: 5, name: 'やみのちから'},
  {albumIndex: 2, track: 6, name: '幻夢界'},
  {albumIndex: 2, track: 7, name: '死を賭して'},
  {albumIndex: 2, track: 8, name: 'ひもろぎ、むらさきにもえ'},
  {albumIndex: 2, track: 9, name: '恋色マジック'},
  {albumIndex: 2, track: 10, name: '東方封魔録　～幽幻乱舞'},
  {albumIndex: 2, track: 11, name: 'Complete Darkness'},
  {albumIndex: 2, track: 12, name: 'エキストララブ'},
  {albumIndex: 2, track: 13, name: '戦車むすめのみるゆめ'},
  {albumIndex: 2, track: 14, name: '遠野の森'},
  {albumIndex: 2, track: 15, name: '昔話わんだーらんど'},
  {albumIndex: 2, track: 16, name: '博麗神社境内'},
  {albumIndex: 2, track: 17, name: '陽落ちて'},
  {albumIndex: 2, track: 18, name: '封魔終演'},

  {albumIndex: 3, track: 1, name: '夢は時空を越えて'},
  {albumIndex: 3, track: 2, name: 'Selection'},
  {albumIndex: 3, track: 3, name: '東方妖恋談'},
  {albumIndex: 3, track: 4, name: 'Reincarnation'},
  {albumIndex: 3, track: 5, name: 'Dim. Dream'},
  {albumIndex: 3, track: 6, name: 'Tabula rasa　～空白少女'},
  {albumIndex: 3, track: 7, name: 'Maniacal Princess'},
  {albumIndex: 3, track: 8, name: '夢消失　～Lost Dream'},
  {albumIndex: 3, track: 9, name: '夢幻遊戯　～Dream War'},
  {albumIndex: 3, track: 10, name: '魔法決戦！　～Fight it out!'},
  {albumIndex: 3, track: 11, name: 'Sailor of Time'},
  {albumIndex: 3, track: 12, name: 'Strawberry Crisis!!'},
  {albumIndex: 3, track: 13, name: '非統一魔法世界論'},
  {albumIndex: 3, track: 14, name: '魔法鐘愛'},
  {albumIndex: 3, track: 15, name: '久遠の夢'},
  {albumIndex: 3, track: 16, name: '東方の青い空'},
  {albumIndex: 3, track: 17, name: '永遠の満月'},
  {albumIndex: 3, track: 18, name: 'Maple Dream...'},
  {albumIndex: 3, track: 19, name: '霊人の休日'},
  {albumIndex: 3, track: 20, name: '勝利デモ'},
  {albumIndex: 3, track: 21, name: 'ゲームオーバー'},
  {albumIndex: 3, track: 22, name: '時の風'},
  {albumIndex: 3, track: 23, name: 'スターボウドリーム'},
  {albumIndex: 3, track: 24, name: 'Phantasmagoria'},

  {albumIndex: 4, track: 1, name: '幻想郷　～ Lotus Land Story'},
  {albumIndex: 4, track: 2, name: 'Witching Dream'},
  {albumIndex: 4, track: 3, name: 'Selene\'s light'},
  {albumIndex: 4, track: 4, name: '装飾戦　～ Decoration Battle'},
  {albumIndex: 4, track: 5, name: 'Break the Sabbath'},
  {albumIndex: 4, track: 6, name: '紅響曲　～ Scarlet Phoneme'},
  {albumIndex: 4, track: 7, name: 'Bad Apple!!'},
  {albumIndex: 4, track: 8, name: '霊戦　～ Perdition crisis'},
  {albumIndex: 4, track: 9, name: 'アリスマエステラ'},
  {albumIndex: 4, track: 10, name: '少女綺想曲　～ Capriccio'},
  {albumIndex: 4, track: 11, name: '星の器　～ Casket of Star'},
  {albumIndex: 4, track: 12, name: 'Lotus Love'},
  {albumIndex: 4, track: 13, name: '眠れる恐怖　～Sleeping Terror'},
  {albumIndex: 4, track: 14, name: 'Dream Land'},
  {albumIndex: 4, track: 15, name: '幽夢　～ Inanimate Dream'},
  {albumIndex: 4, track: 16, name: '禁じざるをえない遊戯'},
  {albumIndex: 4, track: 17, name: 'メイド幻想　～ Icemilk Magic'},
  {albumIndex: 4, track: 18, name: 'かわいい悪魔　～ Innocence'},
  {albumIndex: 4, track: 19, name: 'Days'},
  {albumIndex: 4, track: 20, name: 'Peaceful'},
  {albumIndex: 4, track: 21, name: 'Arcadian Dream'},
  {albumIndex: 4, track: 22, name: '幻想の住人'},
  {albumIndex: 4, track: 23, name: 'Lotus Road'},
  {albumIndex: 4, track: 24, name: 'Dreamy pilot'},
  {albumIndex: 4, track: 25, name: 'Incomplete Plot'},
  {albumIndex: 4, track: 26, name: 'Border Land'},
  {albumIndex: 4, track: 27, name: 'Magic Shop of Raspberry'},
  {albumIndex: 4, track: 28, name: 'Crescent Dream'},

  {albumIndex: 5, track: 1, name: '怪綺談　～ Mystic Square'},
  {albumIndex: 5, track: 2, name: 'Dream Express'},
  {albumIndex: 5, track: 3, name: '魔法陣　～ Magic Square'},
  {albumIndex: 5, track: 4, name: '夢想時空'},
  {albumIndex: 5, track: 5, name: '霊天　～ Spiritual Heaven'},
  {albumIndex: 5, track: 6, name: 'Romantic Children'},
  {albumIndex: 5, track: 7, name: 'プラスチックマインド'},
  {albumIndex: 5, track: 8, name: 'メイプルワイズ'},
  {albumIndex: 5, track: 9, name: '禁断の魔法　～ Forbidden Magic'},
  {albumIndex: 5, track: 10, name: '真紅の少女　～ Crimson Dead!!'},
  {albumIndex: 5, track: 11, name: '裏切りの少女　～ Judas Kiss'},
  {albumIndex: 5, track: 12, name: 'the Last Judgement'},
  {albumIndex: 5, track: 13, name: '悲しき人形　～ Doll of Misery'},
  {albumIndex: 5, track: 14, name: '世界の果て　～ World\'s End'},
  {albumIndex: 5, track: 15, name: '神話幻想　～ Infinite Being'},
  {albumIndex: 5, track: 16, name: '不思議の国のアリス'},
  {albumIndex: 5, track: 17, name: 'the Grimoire of Alice'},
  {albumIndex: 5, track: 18, name: '神社'},
  {albumIndex: 5, track: 19, name: 'Endless'},
  {albumIndex: 5, track: 20, name: '久遠の楽園'},
  {albumIndex: 5, track: 21, name: 'Mystic Dream'},
  {albumIndex: 5, track: 22, name: 'Peaceful Romancer'},
  {albumIndex: 5, track: 23, name: '魂の休らむ所'},

  {albumIndex: 6, track: 1, name: '赤より紅い夢'},
  {albumIndex: 6, track: 2, name: 'ほおずきみたいに紅い魂'},
  {albumIndex: 6, track: 3, name: '妖魔夜行'},
  {albumIndex: 6, track: 4, name: 'ルーネイトエルフ'},
  {albumIndex: 6, track: 5, name: 'おてんば恋娘'},
  {albumIndex: 6, track: 6, name: '上海紅茶館　～ Chinese Tea'},
  {albumIndex: 6, track: 7, name: '明治十七年の上海アリス'},
  {albumIndex: 6, track: 8, name: 'ヴワル魔法図書館'},
  {albumIndex: 6, track: 9, name: 'ラクトガール　～ 少女密室'},
  {albumIndex: 6, track: 10, name: 'メイドと血の懐中時計'},
  {albumIndex: 6, track: 11, name: '月時計　～ ルナ・ダイアル'},
  {albumIndex: 6, track: 12, name: 'ツェペシュの幼き末裔'},
  {albumIndex: 6, track: 13, name: '亡き王女の為のセプテット'},
  {albumIndex: 6, track: 14, name: '魔法少女達の百年祭'},
  {albumIndex: 6, track: 15, name: 'U.N.オーエンは彼女なのか？'},
  {albumIndex: 6, track: 16, name: '紅より儚い永遠'},
  {albumIndex: 6, track: 17, name: '紅楼　～ Eastern Dream...'},

  {albumIndex: 7, track: 1, name: '妖々夢　～ Snow or Cherry Petal'},
  {albumIndex: 7, track: 2, name: '無何有の郷　～ Deep Mountain'},
  {albumIndex: 7, track: 3, name: 'クリスタライズシルバー'},
  {albumIndex: 7, track: 4, name: '遠野幻想物語'},
  {albumIndex: 7, track: 5, name: 'ティアオイエツォン(withered leaf)'},
  {albumIndex: 7, track: 6, name: 'ブクレシュティの人形師'},
  {albumIndex: 7, track: 7, name: '人形裁判　～ 人の形弄びし少女'},
  {albumIndex: 7, track: 8, name: '天空の花の都'},
  {albumIndex: 7, track: 9, name: '幽霊楽団　～ Phantom Ensemble'},
  {albumIndex: 7, track: 10, name: '東方妖々夢　～ Ancient Temple'},
  {albumIndex: 7, track: 11, name: '広有射怪鳥事　～ Till When?'},
  {albumIndex: 7, track: 12, name: 'アルティメットトゥルース'},
  {albumIndex: 7, track: 13, name: '幽雅に咲かせ、墨染の桜　～ Border of Life'},
  {albumIndex: 7, track: 14, name: 'ボーダーオブライフ'},
  {albumIndex: 7, track: 15, name: '妖々跋扈'},
  {albumIndex: 7, track: 16, name: '少女幻葬　～ Necro-Fantasy'},
  {albumIndex: 7, track: 17, name: '妖々跋扈　～ Who done it!'},
  {albumIndex: 7, track: 18, name: 'ネクロファンタジア'},
  {albumIndex: 7, track: 19, name: '春風の夢'},
  {albumIndex: 7, track: 20, name: 'さくらさくら　～ Japanize Dream...'},

  {albumIndex: 8, track: 1, name: '永夜抄　～ Eastern Night.'},
  {albumIndex: 8, track: 2, name: '幻視の夜　～ Ghostly Eyes'},
  {albumIndex: 8, track: 3, name: '蠢々秋月　～ Mooned Insect'},
  {albumIndex: 8, track: 4, name: '夜雀の歌声　～ Night Bird'},
  {albumIndex: 8, track: 5, name: 'もう歌しか聞こえない'},
  {albumIndex: 8, track: 6, name: '懐かしき東方の血　～ Old World'},
  {albumIndex: 8, track: 7, name: 'プレインエイジア'},
  {albumIndex: 8, track: 8, name: '永夜の報い　～ Imperishable Night'},
  {albumIndex: 8, track: 9, name: '少女綺想曲　～ Dream Battle'},
  {albumIndex: 8, track: 10, name: '恋色マスタースパーク'},
  {albumIndex: 8, track: 11, name: 'シンデレラケージ　～ Kagome-Kagome'},
  {albumIndex: 8, track: 12, name: '狂気の瞳　～ Invisible Full Moon'},
  {albumIndex: 8, track: 13, name: 'ヴォヤージュ1969'},
  {albumIndex: 8, track: 14, name: '千年幻想郷　～ History of the Moon'},
  {albumIndex: 8, track: 15, name: '竹取飛翔　～ Lunatic Princess'},
  {albumIndex: 8, track: 16, name: 'ヴォヤージュ1970'},
  {albumIndex: 8, track: 17, name: 'エクステンドアッシュ　～ 蓬莱人'},
  {albumIndex: 8, track: 18, name: '月まで届け、不死の煙'},
  {albumIndex: 8, track: 19, name: '月見草'},
  {albumIndex: 8, track: 20, name: 'Eternal Dream　～ 幽玄の槭樹'},
  {albumIndex: 8, track: 21, name: '東方妖怪小町'},

  {albumIndex: 9, track: 1, name: '花映塚　～ Higan Retour'},
  {albumIndex: 9, track: 2, name: '春色小径　～ Colorful Path'},
  {albumIndex: 9, track: 3, name: 'オリエンタルダークフライト'},
  {albumIndex: 9, track: 4, name: 'フラワリングナイト'},
  {albumIndex: 9, track: 5, name: '東方妖々夢　～ Ancient Temple'},
  {albumIndex: 9, track: 6, name: '狂気の瞳　～ Invisible Full Moon'},
  {albumIndex: 9, track: 7, name: 'おてんば恋娘の冒険'},
  {albumIndex: 9, track: 8, name: '幽霊楽団　～ Phantom Ensemble'},
  {albumIndex: 9, track: 9, name: 'もう歌しか聞こえない　～ Flower Mix'},
  {albumIndex: 9, track: 10, name: 'お宇佐さまの素い幡'},
  {albumIndex: 9, track: 11, name: '風神少女(Short Version)'},
  {albumIndex: 9, track: 12, name: 'ポイズンボディ　～ Forsaken Doll'},
  {albumIndex: 9, track: 13, name: '今昔幻想郷　～ Flower Land'},
  {albumIndex: 9, track: 14, name: '彼岸帰航　～ Riverside View'},
  {albumIndex: 9, track: 15, name: '六十年目の東方裁判　～ Fate of Sixty Years'},
  {albumIndex: 9, track: 16, name: '花の映る塚'},
  {albumIndex: 9, track: 17, name: '此岸の塚'},
  {albumIndex: 9, track: 18, name: '花は幻想のままに'},
  {albumIndex: 9, track: 19, name: '魂の花　～ Another Dream...'},

  {albumIndex: 10, track: 1, name: '封印されし神々'},
  {albumIndex: 10, track: 2, name: '人恋し神様　～ Romantic Fall'},
  {albumIndex: 10, track: 3, name: '稲田姫様に叱られるから'},
  {albumIndex: 10, track: 4, name: '厄神様の通り道　～ Dark Road'},
  {albumIndex: 10, track: 5, name: '運命のダークサイド'},
  {albumIndex: 10, track: 6, name: '神々が恋した幻想郷'},
  {albumIndex: 10, track: 7, name: '芥川龍之介の河童　～ Candid Friend'},
  {albumIndex: 10, track: 8, name: 'フォールオブフォール　～ 秋めく滝'},
  {albumIndex: 10, track: 9, name: '妖怪の山　～ Mysterious Mountain'},
  {albumIndex: 10, track: 10, name: '少女が見た日本の原風景'},
  {albumIndex: 10, track: 11, name: '信仰は儚き人間の為に'},
  {albumIndex: 10, track: 12, name: '御柱の墓場　～ Grave of Being'},
  {albumIndex: 10, track: 13, name: '神さびた古戦場　～ Suwa Foughten Field'},
  {albumIndex: 10, track: 14, name: '明日ハレの日、ケの昨日'},
  {albumIndex: 10, track: 15, name: 'ネイティブフェイス'},
  {albumIndex: 10, track: 16, name: '麓の神社'},
  {albumIndex: 10, track: 17, name: '神は恵みの雨を降らす　～ Sylphid Dream'},
  {albumIndex: 10, track: 18, name: 'プレイヤーズスコア'},

  {albumIndex: 11, track: 1, name: '地霊達の起床'},
  {albumIndex: 11, track: 2, name: '暗闇の風穴'},
  {albumIndex: 11, track: 3, name: '封じられた妖怪　～ Lost Place'},
  {albumIndex: 11, track: 4, name: '渡る者の途絶えた橋'},
  {albumIndex: 11, track: 5, name: '緑眼のジェラシー'},
  {albumIndex: 11, track: 6, name: '旧地獄街道を行く'},
  {albumIndex: 11, track: 7, name: '華のさかづき大江山'},
  {albumIndex: 11, track: 8, name: 'ハートフェルトファンシー'},
  {albumIndex: 11, track: 9, name: '少女さとり　～ 3rd eye'},
  {albumIndex: 11, track: 10, name: '廃獄ララバイ'},
  {albumIndex: 11, track: 11, name: '死体旅行　～ Be of good cheer!'},
  {albumIndex: 11, track: 12, name: '業火マントル'},
  {albumIndex: 11, track: 13, name: '霊知の太陽信仰　～ Nuclear Fusion'},
  {albumIndex: 11, track: 14, name: 'ラストリモート'},
  {albumIndex: 11, track: 15, name: 'ハルトマンの妖怪少女'},
  {albumIndex: 11, track: 16, name: '地霊達の帰宅'},
  {albumIndex: 11, track: 17, name: 'エネルギー黎明　～ Future Dream...'},
  {albumIndex: 11, track: 18, name: 'プレイヤーズスコア'},

  {albumIndex: 12, track: 1, name: '青空の影'},
  {albumIndex: 12, track: 2, name: '春の湊に'},
  {albumIndex: 12, track: 3, name: '小さな小さな賢将'},
  {albumIndex: 12, track: 4, name: '閉ざせし雲の通い路'},
  {albumIndex: 12, track: 5, name: '万年置き傘にご注意を'},
  {albumIndex: 12, track: 6, name: 'スカイルーイン'},
  {albumIndex: 12, track: 7, name: '時代親父とハイカラ少女'},
  {albumIndex: 12, track: 8, name: '幽霊客船の時空を越えた旅'},
  {albumIndex: 12, track: 9, name: 'キャプテン・ムラサ'},
  {albumIndex: 12, track: 10, name: '魔界地方都市エソテリア'},
  {albumIndex: 12, track: 11, name: '虎柄の毘沙門天'},
  {albumIndex: 12, track: 12, name: '法界の火'},
  {albumIndex: 12, track: 13, name: '感情の摩天楼　～ Cosmic Mind'},
  {albumIndex: 12, track: 14, name: '夜空のユーフォーロマンス'},
  {albumIndex: 12, track: 15, name: '平安のエイリアン'},
  {albumIndex: 12, track: 16, name: '妖怪寺'},
  {albumIndex: 12, track: 17, name: '空の帰り道　～ Sky Dream'},
  {albumIndex: 12, track: 18, name: 'プレイヤーズスコア'},

  {albumIndex: 13, track: 1, name: '欲深き霊魂'},
  {albumIndex: 13, track: 2, name: '死霊の夜桜'},
  {albumIndex: 13, track: 3, name: 'ゴーストリード'},
  {albumIndex: 13, track: 4, name: '妖怪寺へようこそ'},
  {albumIndex: 13, track: 5, name: '門前の妖怪小娘'},
  {albumIndex: 13, track: 6, name: '素敵な墓場で暮しましょ'},
  {albumIndex: 13, track: 7, name: 'リジッドパラダイス'},
  {albumIndex: 13, track: 8, name: 'デザイアドライブ'},
  {albumIndex: 13, track: 9, name: '古きユアンシェン'},
  {albumIndex: 13, track: 10, name: '夢殿大祀廟'},
  {albumIndex: 13, track: 11, name: '大神神話伝'},
  {albumIndex: 13, track: 12, name: '小さな欲望の星空'},
  {albumIndex: 13, track: 13, name: '聖徳伝説　～ True Administrator'},
  {albumIndex: 13, track: 14, name: '妖怪裏参道'},
  {albumIndex: 13, track: 15, name: '佐渡の二ッ岩'},
  {albumIndex: 13, track: 16, name: '神社の新しい風'},
  {albumIndex: 13, track: 17, name: 'デザイアドリーム'},
  {albumIndex: 13, track: 18, name: 'プレイヤーズスコア'},

  {albumIndex: 14, track: 1, name: '不思議なお祓い棒'},
  {albumIndex: 14, track: 2, name: 'ミストレイク'},
  {albumIndex: 14, track: 3, name: '秘境のマーメイド'},
  {albumIndex: 14, track: 4, name: '運河を行き交う人妖'},
  {albumIndex: 14, track: 5, name: '柳の下のデュラハン'},
  {albumIndex: 14, track: 6, name: '満月の竹林'},
  {albumIndex: 14, track: 7, name: '孤独なウェアウルフ'},
  {albumIndex: 14, track: 8, name: 'マジカルストーム'},
  {albumIndex: 14, track: 9, name: '幻想浄瑠璃'},
  {albumIndex: 14, track: 10, name: '空中に沈む輝針城'},
  {albumIndex: 14, track: 11, name: 'リバースイデオロギー'},
  {albumIndex: 14, track: 12, name: '針小棒大の天守閣'},
  {albumIndex: 14, track: 13, name: '輝く針の小人族　～ Little Princess'},
  {albumIndex: 14, track: 14, name: '魔力の雷雲'},
  {albumIndex: 14, track: 15, name: '始原のビート　～ Pristine Beat'},
  {albumIndex: 14, track: 16, name: '小槌の魔力'},
  {albumIndex: 14, track: 17, name: '不思議な不思議な道具達'},
  {albumIndex: 14, track: 18, name: 'プレイヤーズスコア'},

  {albumIndex: 15, track: 1, name: '宇宙巫女現る'},
  {albumIndex: 15, track: 2, name: '忘れがたき、よすがの緑'},
  {albumIndex: 15, track: 3, name: '兎は舞い降りた'},
  {albumIndex: 15, track: 4, name: '湖は浄めの月光を映して'},
  {albumIndex: 15, track: 5, name: '九月のパンプキン'},
  {albumIndex: 15, track: 6, name: '宇宙を飛ぶ不思議な巫女'},
  {albumIndex: 15, track: 7, name: '永遠の春夢'},
  {albumIndex: 15, track: 8, name: '凍り付いた永遠の都'},
  {albumIndex: 15, track: 9, name: '逆転するホイールオブフォーチュン'},
  {albumIndex: 15, track: 10, name: '遥か３８万キロのボヤージュ'},
  {albumIndex: 15, track: 11, name: '星条旗のピエロ'},
  {albumIndex: 15, track: 12, name: '故郷の星が映る海'},
  {albumIndex: 15, track: 13, name: 'ピュアヒューリーズ　～ 心の在処'},
  {albumIndex: 15, track: 14, name: '見た事も無い悪夢の世界'},
  {albumIndex: 15, track: 15, name: 'パンデモニックプラネット'},
  {albumIndex: 15, track: 16, name: '神社から見える月'},
  {albumIndex: 15, track: 17, name: '宇宙巫女帰還する'},
  {albumIndex: 15, track: 18, name: 'プレイヤーズスコア'},

  {albumIndex: 16, track: 1, name: '桜舞い散る天空'},
  {albumIndex: 16, track: 2, name: '希望の星は青霄に昇る'},
  {albumIndex: 16, track: 3, name: '真夏の妖精の夢'},
  {albumIndex: 16, track: 4, name: '色無き風は妖怪の山に'},
  {albumIndex: 16, track: 5, name: '山奥のエンカウンター'},
  {albumIndex: 16, track: 6, name: '桜色の海を泳いで'},
  {albumIndex: 16, track: 7, name: '一対の神獣'},
  {albumIndex: 16, track: 8, name: '幻想のホワイトトラベラー'},
  {albumIndex: 16, track: 9, name: '魔法の笠地蔵'},
  {albumIndex: 16, track: 10, name: '禁断の扉の向こうは、この世かあの世か'},
  {albumIndex: 16, track: 11, name: 'クレイジーバックダンサーズ'},
  {albumIndex: 16, track: 12, name: 'イントゥ・バックドア'},
  {albumIndex: 16, track: 13, name: '秘匿されたフォーシーズンズ'},
  {albumIndex: 16, track: 14, name: 'もうドアには入れない'},
  {albumIndex: 16, track: 15, name: '秘神マターラ　～ Hidden Star in All Seasons'},
  {albumIndex: 16, track: 16, name: '不自然な自然'},
  {albumIndex: 16, track: 17, name: '白い旅人'},

  {albumIndex: 17, track: 1, name: '物言わぬ獣の霊'},
  {albumIndex: 17, track: 2, name: '地蔵だけが知る哀嘆'},
  {albumIndex: 17, track: 3, name: 'ジェリーストーン'},
  {albumIndex: 17, track: 4, name: 'ロストリバー'},
  {albumIndex: 17, track: 5, name: '石の赤子と水中の牛'},
  {albumIndex: 17, track: 6, name: '不朽の曼珠沙華'},
  {albumIndex: 17, track: 7, name: 'セラフィックチキン'},
  {albumIndex: 17, track: 8, name: 'アンロケイテッドヘル'},
  {albumIndex: 17, track: 9, name: 'トータスドラゴン　～ 幸運と不運'},
  {albumIndex: 17, track: 10, name: 'ビーストメトロポリス'},
  {albumIndex: 17, track: 11, name: 'セラミックスの杖刀人'},
  {albumIndex: 17, track: 12, name: 'エレクトリックヘリテージ'},
  {albumIndex: 17, track: 13, name: '偶像に世界を委ねて　～ Idoratrize World'},
  {albumIndex: 17, track: 14, name: '輝かしき弱肉強食の掟'},
  {albumIndex: 17, track: 15, name: '聖徳太子のペガサス　～ Dark Pegasus'},
  {albumIndex: 17, track: 16, name: '畜生達の休息'},
  {albumIndex: 17, track: 17, name: '地下からの帰還'},

  {albumIndex: 401, track: 1, name: '萃夢想'},
  {albumIndex: 401, track: 2, name: '東方妖恋談'},
  {albumIndex: 401, track: 3, name: '少女綺想曲　～ Capriccio'},
  {albumIndex: 401, track: 4, name: '恋色マジック'},
  {albumIndex: 401, track: 5, name: '魔女達の舞踏会'},
  {albumIndex: 401, track: 6, name: 'メイドと血の懐中時計'},
  {albumIndex: 401, track: 7, name: '月時計　～ ルナ・ダイアル'},
  {albumIndex: 401, track: 8, name: 'ブクレシュティの人形師'},
  {albumIndex: 401, track: 9, name: '人形裁判'},
  {albumIndex: 401, track: 10, name: 'ラクトガール　～ 少女密室'},
  {albumIndex: 401, track: 11, name: 'ヴワル魔法図書館'},
  {albumIndex: 401, track: 12, name: '広有射怪鳥事　～ Till When?'},
  {albumIndex: 401, track: 13, name: '東方妖々夢　～ Ancient Temple'},
  {albumIndex: 401, track: 14, name: '亡き王女の為のセプテット'},
  {albumIndex: 401, track: 15, name: '幽雅に咲かせ、墨染の桜　～ Border of Life'},
  {albumIndex: 401, track: 16, name: 'Demystify Feast'},
  {albumIndex: 401, track: 17, name: '夜が降りてくる　～ Evening Star'},
  {albumIndex: 401, track: 18, name: '御伽の国の鬼が島　～ Missing Power'},
  {albumIndex: 401, track: 19, name: '夏明き'},
  {albumIndex: 401, track: 20, name: '東方萃夢想'},
  {albumIndex: 401, track: 21, name: '魔所'},
  {albumIndex: 401, track: 22, name: '月輪'},
  {albumIndex: 401, track: 23, name: '遍参'},
  {albumIndex: 401, track: 24, name: '裏心'},
  {albumIndex: 401, track: 25, name: 'Intermezzo'},
  {albumIndex: 401, track: 26, name: 'あゆのかぜ'},
  {albumIndex: 401, track: 27, name: '森閑'},
  {albumIndex: 401, track: 28, name: '仰空'},
  {albumIndex: 401, track: 29, name: '幽境'},
  {albumIndex: 401, track: 30, name: '珍客'},
  {albumIndex: 401, track: 31, name: '紅夜'},
  {albumIndex: 401, track: 32, name: '戦迅'},
  {albumIndex: 401, track: 33, name: '禍機'},
  {albumIndex: 401, track: 34, name: '砕月'},

  {albumIndex: 402, track: 1, name: '天狗の手帖　～ Mysterious Note'},
  {albumIndex: 402, track: 2, name: '風の循環　～ Wind Tour'},
  {albumIndex: 402, track: 3, name: '天狗が見ている　～ Black Eyes'},
  {albumIndex: 402, track: 4, name: '東の国の眠らない夜'},
  {albumIndex: 402, track: 5, name: 'レトロスペクティブ京都'},
  {albumIndex: 402, track: 6, name: '風神少女'},

  {albumIndex: 403, track: 1, name: '緋想天'},
  {albumIndex: 403, track: 2, name: '日常坐臥'},
  {albumIndex: 403, track: 3, name: '地の色は黄色'},
  {albumIndex: 403, track: 4, name: '甲論乙駁'},
  {albumIndex: 403, track: 5, name: '風光明媚'},
  {albumIndex: 403, track: 6, name: '香る樹葉花'},
  {albumIndex: 403, track: 7, name: '踊る水飛沫'},
  {albumIndex: 403, track: 8, name: '以魚駆蠅'},
  {albumIndex: 403, track: 9, name: '放縦不羈'},
  {albumIndex: 403, track: 10, name: '嘲りの遊戯'},
  {albumIndex: 403, track: 11, name: '冷吟閑酔'},
  {albumIndex: 403, track: 12, name: '雲外蒼天'},
  {albumIndex: 403, track: 13, name: '黒い海に紅く　～ Legendary Fish'},
  {albumIndex: 403, track: 14, name: '天衣無縫'},
  {albumIndex: 403, track: 15, name: '有頂天変　～ Wonderful Heaven'},
  {albumIndex: 403, track: 16, name: '幼心地の有頂天'},
  {albumIndex: 403, track: 17, name: '暮色蒼然'},
  {albumIndex: 403, track: 18, name: '東方緋想天'},
  {albumIndex: 403, track: 19, name: '東方妖恋談'},
  {albumIndex: 403, track: 20, name: '星の器　～ Casket of Star'},
  {albumIndex: 403, track: 21, name: 'フラワリングナイト'},
  {albumIndex: 403, track: 22, name: 'ブクレシュティの人形師'},
  {albumIndex: 403, track: 23, name: '広有射怪鳥事　～ Till When?'},
  {albumIndex: 403, track: 24, name: 'ラクトガール　～ 少女密室'},
  {albumIndex: 403, track: 25, name: '幽雅に咲かせ、墨染の桜　～ Border of Life'},
  {albumIndex: 403, track: 26, name: '亡き王女の為のセプテット'},
  {albumIndex: 403, track: 27, name: '夜が降りてくる'},
  {albumIndex: 403, track: 28, name: '砕月'},
  {albumIndex: 403, track: 29, name: '狂気の瞳　～ Invisible Full Moon'},
  {albumIndex: 403, track: 30, name: '風神少女'},
  {albumIndex: 403, track: 31, name: '彼岸帰航　～ Riverside View'},

  {albumIndex: 404, track: 1, name: '君はあの影を見たか'},
  {albumIndex: 404, track: 2, name: '萃夢想'},
  {albumIndex: 404, track: 3, name: '伝説の巨神'},
  {albumIndex: 404, track: 4, name: 'ぼくらの非想天則'},
  {albumIndex: 404, track: 5, name: '人形のある風景'},
  {albumIndex: 404, track: 6, name: '悠久の蒸気機関'},
  {albumIndex: 404, track: 7, name: '信仰は儚き人間の為に'},
  {albumIndex: 404, track: 8, name: 'おてんば恋娘'},
  {albumIndex: 404, track: 9, name: '上海紅茶館　～ Chinese Tea'},
  {albumIndex: 404, track: 10, name: '霊知の太陽信仰　～ Nuclear Fusion'},
  {albumIndex: 404, track: 11, name: '明日ハレの日、ケの昨日'},
  {albumIndex: 404, track: 12, name: 'アンノウンＸ　～ Unfound Adventure'},
  {albumIndex: 404, track: 13, name: '空に浮かぶ物体Ｘ'},
  {albumIndex: 404, track: 14, name: '二色蓮花蝶　～ Ancients'},
  {albumIndex: 404, track: 15, name: '恋色マジック'},
  {albumIndex: 404, track: 16, name: 'the Grimoire of Alice'},
  {albumIndex: 404, track: 17, name: 'ヴワル魔法図書館'},
  {albumIndex: 404, track: 18, name: '東方妖恋談'},
  {albumIndex: 404, track: 19, name: '巨大な影と小さな結末'},

  {albumIndex: 405, track: 1, name: 'ニュースハウンド'},
  {albumIndex: 405, track: 2, name: 'あなたの町の怪事件'},
  {albumIndex: 405, track: 3, name: '妖怪モダンコロニー'},
  {albumIndex: 405, track: 4, name: 'ネメシスの要塞'},
  {albumIndex: 405, track: 5, name: '無間の鐘　～ Infinite Nightmare'},
  {albumIndex: 405, track: 6, name: '妖怪の山　～ Mysterious Mountain'},
  {albumIndex: 405, track: 7, name: '曲名不詳'},

  {albumIndex: 406, track: 1, name: '春の氷精'},
  {albumIndex: 406, track: 2, name: '可愛い大戦争のリフレーン'},
  {albumIndex: 406, track: 3, name: 'いたずらに命をかけて'},
  {albumIndex: 406, track: 4, name: '年中夢中の好奇心'},
  {albumIndex: 406, track: 5, name: '真夜中のフェアリーダンス'},
  {albumIndex: 406, track: 6, name: '妖精大戦争　～ Fairy Wars'},
  {albumIndex: 406, track: 7, name: 'ルーズレイン'},
  {albumIndex: 406, track: 8, name: 'メイガスナイト'},
  {albumIndex: 406, track: 9, name: '春の氷精　- 静 -'},
  {albumIndex: 406, track: 10, name: 'プレイヤーズスコア'},

  {albumIndex: 407, track: 1, name: '春色小径　～ Colorful Path'},
  {albumIndex: 407, track: 2, name: 'メイガスナイト'},
  {albumIndex: 407, track: 3, name: '時代親父とハイカラ少女'},
  {albumIndex: 407, track: 4, name: '感情の摩天楼　～ Cosmic Mind'},
  {albumIndex: 407, track: 5, name: '大神神話伝'},
  {albumIndex: 407, track: 6, name: '聖徳伝説　～ True Administrator'},
  {albumIndex: 407, track: 7, name: '芥川龍之介の河童　～ Candid Friend'},
  {albumIndex: 407, track: 8, name: 'ハルトマンの妖怪少女'},
  {albumIndex: 407, track: 9, name: '佐渡の二ッ岩'},
  {albumIndex: 407, track: 10, name: '幻想郷の二ッ岩'},
  {albumIndex: 407, track: 11, name: '亡失のエモーション'},
  {albumIndex: 407, track: 12, name: '塵界不変のペシミズム'},
  {albumIndex: 407, track: 13, name: '心綺楼囃子'},
  {albumIndex: 407, track: 14, name: '人気のある場所'},
  {albumIndex: 407, track: 15, name: '人気のない場所'},
  {albumIndex: 407, track: 16, name: '丑三つ時の里'},
  {albumIndex: 407, track: 17, name: '本日の一面記事'},
  {albumIndex: 407, track: 18, name: '暁雲'},
  {albumIndex: 407, track: 19, name: '官板黄昏新聞'},

  {albumIndex: 408, track: 1, name: '反則の狼煙を上げろ'},
  {albumIndex: 408, track: 2, name: '不可能弾幕には反則を'},
  {albumIndex: 408, track: 3, name: 'ミッドナイトスペルカード'},
  {albumIndex: 408, track: 4, name: 'ロマンチック逃飛行'},
  {albumIndex: 408, track: 5, name: '永遠の三日天下'},
  {albumIndex: 408, track: 6, name: '秘境のマーメイド'},
  {albumIndex: 408, track: 7, name: 'リバースイデオロギー'},
  {albumIndex: 408, track: 8, name: '幻想浄瑠璃'},
  {albumIndex: 408, track: 9, name: '妖怪の山　～ Mysterious Mountain'},
  {albumIndex: 408, track: 10, name: 'プレイヤーズスコア'},

  {albumIndex: 409, track: 1, name: '二色蓮花蝶　～ Red and White'},
  {albumIndex: 409, track: 2, name: '恋色マスタースパーク'},
  {albumIndex: 409, track: 3, name: '時代親父とハイカラ少女'},
  {albumIndex: 409, track: 4, name: '感情の摩天楼　～ Cosmic Mind'},
  {albumIndex: 409, track: 5, name: '大神神話伝'},
  {albumIndex: 409, track: 6, name: '聖徳伝説　～ True Administrator'},
  {albumIndex: 409, track: 7, name: '芥川龍之介の河童　～ Candid Friend'},
  {albumIndex: 409, track: 8, name: 'ハルトマンの妖怪少女'},
  {albumIndex: 409, track: 9, name: '幻想郷の二ッ岩'},
  {albumIndex: 409, track: 10, name: '亡失のエモーション'},
  {albumIndex: 409, track: 11, name: '月まで届け、不死の煙'},
  {albumIndex: 409, track: 12, name: '輝く針の小人族　～ Little Princess'},
  {albumIndex: 409, track: 13, name: '心揺さぶる都市伝説'},
  {albumIndex: 409, track: 14, name: '幻想郷ふしぎ発見'},
  {albumIndex: 409, track: 15, name: 'ボールのある日常'},
  {albumIndex: 409, track: 16, name: '顕現した伝承の形'},
  {albumIndex: 409, track: 17, name: '時代の風の訪れ'},
  {albumIndex: 409, track: 18, name: '価値がわからない'},
  {albumIndex: 409, track: 19, name: '可能性を信じて'},
  {albumIndex: 409, track: 20, name: '真実を知る者'},
  {albumIndex: 409, track: 21, name: '外界フォークロア'},
  {albumIndex: 409, track: 22, name: '各々の結末'},
  {albumIndex: 409, track: 23, name: '明かされる深秘'},
  {albumIndex: 409, track: 24, name: 'オカルトアラカルト'},
  {albumIndex: 409, track: 25, name: '七玉蒐集ショウダウン'},
  {albumIndex: 409, track: 26, name: '公正なる奪い合い'},
  {albumIndex: 409, track: 27, name: '対蹠地の鐘'},
  {albumIndex: 409, track: 28, name: '竹林インフレイム'},
  {albumIndex: 409, track: 29, name: '華狭間のバトルフィールド'},
  {albumIndex: 409, track: 30, name: 'ラストオカルティズム　～現し世の秘術師'},

  {albumIndex: 601, track: 1, name: '秋霜玉　～ Clockworks'},
  {albumIndex: 601, track: 2, name: 'フォルスストロベリー'},
  {albumIndex: 601, track: 3, name: 'プリムローズシヴァ'},
  {albumIndex: 601, track: 4, name: '幻想帝都'},
  {albumIndex: 601, track: 5, name: 'ディザストラスジェミニ'},
  {albumIndex: 601, track: 6, name: '華の幻想　紅夢の宙'},
  {albumIndex: 601, track: 7, name: '天空アーミー'},
  {albumIndex: 601, track: 8, name: 'スプートニク幻夜'},
  {albumIndex: 601, track: 9, name: '機械サーカス　～ Reverie'},
  {albumIndex: 601, track: 10, name: 'カナベラルの夢幻少女'},
  {albumIndex: 601, track: 11, name: '魔法少女十字軍'},
  {albumIndex: 601, track: 12, name: 'アンティークテラー'},
  {albumIndex: 601, track: 13, name: '夢機械　～ Innocent Power'},
  {albumIndex: 601, track: 14, name: '幻想科学　～ Doll\'s Phantom'},
  {albumIndex: 601, track: 15, name: '少女神性　～ Pandora\'s Box'},
  {albumIndex: 601, track: 16, name: 'シルクロードアリス'},
  {albumIndex: 601, track: 17, name: '魔女達の舞踏会　～ Magus'},
  {albumIndex: 601, track: 18, name: '二色蓮花蝶　～ Ancients'},
  {albumIndex: 601, track: 19, name: 'ハーセルヴズ'},
  {albumIndex: 601, track: 20, name: 'タイトルドメイド'},

  {albumIndex: 602, track: 1, name: '稀翁玉　～ Fairy Dance'},
  {albumIndex: 602, track: 2, name: '天鵞絨少女戦　～ Velvet Battle'},
  {albumIndex: 602, track: 3, name: 'Castle Explorer -in the Sky-'},
  {albumIndex: 602, track: 4, name: 'オルフェの詩　～ Pseudoclassic'},
  {albumIndex: 602, track: 5, name: '新幻想　～ New Fantasy'},
  {albumIndex: 602, track: 6, name: 'オルレアンの聖騎士'},
  {albumIndex: 602, track: 7, name: 'My Maid, Sweet Maid'},
  {albumIndex: 602, track: 8, name: '桜花之恋塚　～ Flower of Japan'},
  {albumIndex: 602, track: 9, name: '乙女戦士　～ Heart of Valkyrie'},
  {albumIndex: 602, track: 10, name: 'エニグマティクドール　～ God Knows'},

  {albumIndex: 604, track: 1, name: 'AN ORDEAL FROM GOD'},

  {albumIndex: 605, track: 1, name: 'キュアリアス上海古牌'},
  {albumIndex: 605, track: 2, name: '神魔討綺伝 AN ORDEAL FROM GOD'},

  {albumIndex: 701, track: 1, name: 'Witch of Love Potion'},
  {albumIndex: 701, track: 2, name: 'Magical and Hopeless'},
  {albumIndex: 701, track: 3, name: 'Sacred Battle'},

  {albumIndex: 702, track: 1, name: 'step u/b (lazy style)'},
  {albumIndex: 702, track: 2, name: 'step u/b'},
  {albumIndex: 702, track: 3, name: 'Festiv-al-coholically'},
  {albumIndex: 702, track: 4, name: 'Valse Alcoholique'},
  {albumIndex: 702, track: 5, name: 'chase the twilight'},
  {albumIndex: 702, track: 6, name: '呑んべぇのレムリア'},
  {albumIndex: 702, track: 7, name: '絶対大丈夫だよ！！いくら飲んでも朝が来るよ！！。'},

  {albumIndex: 901, track: 1, name: '蓬莱伝説'},
  {albumIndex: 901, track: 2, name: '二色蓮花蝶　～ Red and White'},
  {albumIndex: 901, track: 3, name: '桜花之恋塚　～ Japanese Flower'},
  {albumIndex: 901, track: 4, name: '明治十七年の上海アリス'},
  {albumIndex: 901, track: 5, name: '東方怪奇談'},
  {albumIndex: 901, track: 6, name: 'エニグマティクドール'},
  {albumIndex: 901, track: 7, name: 'サーカスレヴァリエ'},
  {albumIndex: 901, track: 8, name: '人形の森'},
  {albumIndex: 901, track: 9, name: 'Witch of Love Potion'},
  {albumIndex: 901, track: 10, name: 'リーインカーネイション'},
  {albumIndex: 901, track: 11, name: 'U.N.オーエンは彼女なのか？'},
  {albumIndex: 901, track: 12, name: '永遠の巫女'},
  {albumIndex: 901, track: 13, name: '空飛ぶ巫女の不思議な毎日'},

  {albumIndex: 902, track: 1, name: '夜のデンデラ野を逝く'},
  {albumIndex: 902, track: 2, name: '少女秘封倶楽部'},
  {albumIndex: 902, track: 3, name: '東方妖々夢　～ Ancient Temple'},
  {albumIndex: 902, track: 4, name: '古の冥界寺'},
  {albumIndex: 902, track: 5, name: '幻視の夜　～ Ghostly Eyes'},
  {albumIndex: 902, track: 6, name: '魔術師メリー'},
  {albumIndex: 902, track: 7, name: '月の妖鳥、化猫の幻'},
  {albumIndex: 902, track: 8, name: '過去の花　～ Fairy of Flower'},
  {albumIndex: 902, track: 9, name: '魔法少女十字軍'},
  {albumIndex: 902, track: 10, name: '少女幻葬　～ Necro-Fantasy'},
  {albumIndex: 902, track: 11, name: '幻想の永遠祭'},

  {albumIndex: 903, track: 1, name: '童祭　～ Innocent Treasures'},
  {albumIndex: 903, track: 2, name: '華胥の夢'},
  {albumIndex: 903, track: 3, name: '上海紅茶館　～ Chinese Tea'},
  {albumIndex: 903, track: 4, name: 'ヴォヤージュ1969'},
  {albumIndex: 903, track: 5, name: '科学世紀の少年少女'},
  {albumIndex: 903, track: 6, name: '永夜の報い　～ Imperishable Night'},
  {albumIndex: 903, track: 7, name: '夜が降りてくる　～ Evening Star'},
  {albumIndex: 903, track: 8, name: '人形裁判　～ 人の形弄びし少女'},
  {albumIndex: 903, track: 9, name: '夢と現の境界'},
  {albumIndex: 903, track: 10, name: '幻想機械　～ Phantom Factory'},
  {albumIndex: 903, track: 11, name: '幽玄の槭樹　～ Eternal Dream'},

  {albumIndex: 904, track: 1, name: 'ヒロシゲ36号　～ Neo Super-Express'},
  {albumIndex: 904, track: 2, name: '53ミニッツの青い海'},
  {albumIndex: 904, track: 3, name: '竹取飛翔　～ Lunatic Princess'},
  {albumIndex: 904, track: 4, name: '彼岸帰航　～ Riverside View'},
  {albumIndex: 904, track: 5, name: '青木ヶ原の伝説'},
  {albumIndex: 904, track: 6, name: 'お宇佐さまの素い幡'},
  {albumIndex: 904, track: 7, name: '月まで届け不死の煙'},
  {albumIndex: 904, track: 8, name: 'レトロスペクティブ京都'},
  {albumIndex: 904, track: 9, name: 'ラクトガール　～ 少女密室'},
  {albumIndex: 904, track: 10, name: '千年幻想郷　～ History of the Moon'},
  {albumIndex: 904, track: 11, name: '最も澄みわたる空と海'},

  {albumIndex: 905, track: 1, name: '月面ツアーへようこそ'},
  {albumIndex: 905, track: 2, name: '天空のグリニッジ'},
  {albumIndex: 905, track: 3, name: '東の国の眠らない夜'},
  {albumIndex: 905, track: 4, name: '車椅子の未来宇宙'},
  {albumIndex: 905, track: 5, name: 'Demystify Feast'},
  {albumIndex: 905, track: 6, name: '衛星カフェテラス'},
  {albumIndex: 905, track: 7, name: 'G Free'},
  {albumIndex: 905, track: 8, name: '大空魔術　～ Magical Astronomy'},
  {albumIndex: 905, track: 9, name: 'ネクロファンタジア'},
  {albumIndex: 905, track: 10, name: '向こう側の月'},

  {albumIndex: 906, track: 1, name: '未知の花 魅知の旅'},
  {albumIndex: 906, track: 2, name: '無間の鐘　～ Infinite Nightmare'},
  {albumIndex: 906, track: 3, name: '明日ハレの日、ケの昨日'},

  {albumIndex: 907, track: 1, name: '衛星トリフネ'},
  {albumIndex: 907, track: 2, name: 'トロヤ群の密林'},
  {albumIndex: 907, track: 3, name: 'デザイアドライブ'},
  {albumIndex: 907, track: 4, name: 'フェアリー冒険譚'},
  {albumIndex: 907, track: 5, name: '天鳥船神社'},
  {albumIndex: 907, track: 6, name: '夜空のユーフォーロマンス'},
  {albumIndex: 907, track: 7, name: 'ハルトマンの妖怪少女'},
  {albumIndex: 907, track: 8, name: '天鳥船神社の結界'},
  {albumIndex: 907, track: 9, name: '感情の摩天楼　～ Cosmic Mind'},
  {albumIndex: 907, track: 10, name: '宇宙に浮かぶ幻想郷'},

  {albumIndex: 908, track: 1, name: '緑のサナトリウム'},
  {albumIndex: 908, track: 2, name: '牛に引かれて善光寺参り'},
  {albumIndex: 908, track: 3, name: 'ハートフェルトファンシー'},
  {albumIndex: 908, track: 4, name: '六十年目の東方裁判　～ Fate of Sixty Years'},
  {albumIndex: 908, track: 5, name: 'アガルタの風'},
  {albumIndex: 908, track: 6, name: 'イザナギオブジェクト'},
  {albumIndex: 908, track: 7, name: '妖怪裏参道'},
  {albumIndex: 908, track: 8, name: 'アンノウンＸ　～ Unfound Adventure'},
  {albumIndex: 908, track: 9, name: '日本中の不思議を集めて'},
  {albumIndex: 908, track: 10, name: '素敵な墓場で暮しましょ'},

  {albumIndex: 909, track: 1, name: '他愛も無い二人の博物誌'},
  {albumIndex: 909, track: 2, name: '凍り付いた永遠の都'},
  {albumIndex: 909, track: 3, name: 'Dr.レイテンシーの眠れなくなる瞳'},
  {albumIndex: 909, track: 4, name: '九月のパンプキン'},
  {albumIndex: 909, track: 5, name: '須臾はプランクを超えて'},
  {albumIndex: 909, track: 6, name: 'シュレディンガーの化猫'},
  {albumIndex: 909, track: 7, name: '空中に沈む輝針城'},
  {albumIndex: 909, track: 8, name: '禁忌の膜壁'},
  {albumIndex: 909, track: 9, name: '故郷の星が映る海'},
  {albumIndex: 909, track: 10, name: 'ピュアヒューリーズ　～ 心の在処'},
  {albumIndex: 909, track: 11, name: '永遠の三日天下'},

  {albumIndex: 910, track: 1, name: 'バー・オールドアダム'},
  {albumIndex: 910, track: 2, name: '燕石博物誌が連れてきた闇'},
  {albumIndex: 910, track: 3, name: 'リバースイデオロギー'},
  {albumIndex: 910, track: 4, name: 'アウトサイダーカクテル'},
  {albumIndex: 910, track: 5, name: '大神神話伝'},
  {albumIndex: 910, track: 6, name: 'パンデモニックプラネット'},
  {albumIndex: 910, track: 7, name: '旧世界の冒険酒場'},
  {albumIndex: 910, track: 8, name: '魔界地方都市エソテリア'},
  {albumIndex: 910, track: 9, name: '亡失のエモーション'},
  {albumIndex: 910, track: 10, name: '二日酔いの同床異夢'},

  {albumIndex: 1304, track: 1, name: 'サニールチルフレクション'},
  {albumIndex: 1304, track: 2, name: '夜だから眠れない'},
  {albumIndex: 1304, track: 3, name: '妖精燦々として'},

  {albumIndex: 1305, track: 1, name: 'サニーミルクの紅霧異変'},
  {albumIndex: 1305, track: 2, name: '雪月桜花の国'},
  {albumIndex: 1305, track: 3, name: 'スターヴォヤージュ208'},

  {albumIndex: 1306, track: 1, name: '可愛い大戦争のリフレーン'},
  {albumIndex: 1306, track: 2, name: 'サニールチルフレクション'},
  {albumIndex: 1306, track: 3, name: '夜だから眠れない'},
  {albumIndex: 1306, track: 4, name: '妖精燦々として'},

  {albumIndex: 1307, track: 1, name: 'フェアリー冒険譚'},
  {albumIndex: 1307, track: 2, name: '二つの世界'},

  {albumIndex: 1308, track: 1, name: '妖怪宇宙旅行'},
  {albumIndex: 1308, track: 2, name: '綿月のスペルカード　～ Lunatic Blue'},
  {albumIndex: 1308, track: 3, name: '呑んべぇのレムリア (Retro Ver)'},

  {albumIndex: 1309, track: 1, name: '魔法使いの憂鬱'},
  {albumIndex: 1309, track: 2, name: 'スプートニク幻夜'},

  {albumIndex: 9999, track: 1, name: '宵闇の魔術師'},
  {albumIndex: 9999, track: 2, name: 'Magic of Life'},
  {albumIndex: 9999, track: 3, name: 'Plastic Space'},
  {albumIndex: 9999, track: 4, name: 'Inventive City'},
  {albumIndex: 9999, track: 5, name: '夢幻回廊'},
  {albumIndex: 9999, track: 6, name: '蓬莱幻想　～ far East'},

  // {'albumIndex': 10000, 'track': 1, 'name': '最終鬼畜妹フランドール・S'},
  // {'albumIndex': 10000, 'track': 2, 'name': '恋色マジック→マスタースパーク'},
];
